[env:esp32s3box3]
platform = espressif32 @ 7.0.0
board = esp32s3box
framework = arduino
board_build.partitions = default_8MB.csv
monitor_speed = 115200
monitor_filters = default
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_ES8311=1
lib_deps = 
	bblanchon/ArduinoJson@^7.0.0
