#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate a compact CJK bitmap font header (cjk_font.h) for the ESP32-S3
medication-reminder firmware.

Strategy
--------
* Source font: a Windows CJK TrueType (simhei.ttf / 黑体).
* We render EVERY printable ASCII char (0x20-0x7E) + EVERY GB2312 Han char
  and full-width punctuation into a 16x16 1-bit dot-matrix glyph.
* Glyphs are stored indexed by Unicode codepoint (sorted ascending) so the
  firmware can binary-search directly from a decoded UTF-8 codepoint - no
  GB2312<->Unicode mapping table needed on the device.
* A preview PNG is also emitted, painting the EXACT glyph bytes the firmware
  will use, so the rendered Chinese can be visually verified on the PC.

Glyph packing (matches firmware reader):
    For row r (0..15), for col c (0..15):
        bit = 1 if pixel lit
    byte0 = bits 15..8  (c=0 is MSB)
    byte1 = bits 7..0   (c=8 is MSB of byte1)
"""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT_H = os.path.join(ROOT, "src", "cjk_font.h")
PREVIEW = os.path.join(HERE, "preview_cjk.png")

W = H = 16
RENDER_SIZE = 64  # render large for quality, then downscale to 16x16
FONT_PATHS = [
    r"C:/Windows/Fonts/simhei.ttf",
    r"C:/Windows/Fonts/simsun.ttc",
    r"C:/Windows/Fonts/msyh.ttc",
]

def pick_font():
    for p in FONT_PATHS:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, RENDER_SIZE), p
            except Exception as e:
                print("font load fail", p, e)
    # last resort: default
    return ImageFont.load_default(), "default"

FONT, FONT_PATH = pick_font()
print("Using font:", FONT_PATH)

def render_glyph(ch):
    """Render ch into a 16x16 1-bit PIL 'L' image (255=lit)."""
    canvas = Image.new("L", (RENDER_SIZE, RENDER_SIZE), 0)
    d = ImageDraw.Draw(canvas)
    try:
        d.text((0, 0), ch, fill=255, font=FONT)
    except Exception:
        return Image.new("L", (W, H), 0)
    bbox = canvas.getbbox()
    if not bbox:
        return Image.new("L", (W, H), 0)
    g = canvas.crop(bbox)
    gw, gh = g.size
    if gw == 0 or gh == 0:
        return Image.new("L", (W, H), 0)
    scale = min(W / gw, H / gh)
    nw, nh = max(1, int(gw * scale)), max(1, int(gh * scale))
    g = g.resize((nw, nh), Image.BILINEAR)
    out = Image.new("L", (W, H), 0)
    out.paste(g, ((W - nw) // 2, (H - nh) // 2))
    return out.point(lambda p: 255 if p > 128 else 0)

def glyph_to_bytes(img):
    """Pack 16x16 1-bit image into 32 bytes (HZK-style)."""
    bits = []
    for r in range(H):
        row = 0
        for c in range(W):
            if img.getpixel((c, r)) > 128:
                row |= (1 << (15 - c))
        bits.append(row)
    data = []
    for row in bits:
        data.append((row >> 8) & 0xFF)
        data.append(row & 0xFF)
    return bytes(data)

# ---- Collect glyphs ----
glyphs = {}  # cp -> 32 bytes

# ASCII printable
for cp in range(0x20, 0x7F):
    ch = chr(cp)
    glyphs[cp] = glyph_to_bytes(render_glyph(ch))

# GB2312 Han + punctuation (q:0xA1..0xF7, w:0xA1..0xFE)
count_gb = 0
for q in range(0xA1, 0xF8):
    for w in range(0xA1, 0xFF):
        try:
            ch = bytes([q, w]).decode("gb2312")
        except Exception:
            continue
        cp = ord(ch)
        if cp in glyphs:
            continue
        glyphs[cp] = glyph_to_bytes(render_glyph(ch))
        count_gb += 1

# fallback box '□' (U+25A1) - synthesize if font lacks it
if 0x25A1 not in glyphs:
    box = Image.new("L", (W, H), 0)
    bd = ImageDraw.Draw(box)
    bd.rectangle([1, 1, W - 2, H - 2], outline=255, width=1)
    glyphs[0x25A1] = glyph_to_bytes(box)

print(f"ASCII glyphs: {0x7F-0x20}  GB2312 glyphs: {count_gb}  total: {len(glyphs)}")

# ---- Sort by codepoint ----
items = sorted(glyphs.items(), key=lambda kv: kv[0])
code_points = [cp for cp, _ in items]
glyph_bytes = b"".join(g for _, g in items)

# ---- Write C header ----
n = len(items)
with open(OUT_H, "w", encoding="utf-8") as f:
    f.write("/*\n")
    f.write(" * cjk_font.h - AUTO-GENERATED compact CJK 16x16 dot-matrix font.\n")
    f.write(" * Source: %s (rendered at %dpx -> 16x16 1-bit).\n" % (os.path.basename(FONT_PATH), RENDER_SIZE))
    f.write(" * Covers ASCII 0x20-0x7E + GB2312 Han/full-width punctuation.\n")
    f.write(" * Indexed by Unicode codepoint (sorted ascending) for binary search.\n")
    f.write(" * Generated by tools/gen_cjk_font.py - DO NOT EDIT BY HAND.\n")
    f.write(" */\n")
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n")
    f.write("#include <pgmspace.h>\n\n")
    f.write("#define CJK_GLYPH_W 16\n")
    f.write("#define CJK_GLYPH_H 16\n")
    f.write("#define CJK_GLYPH_BYTES 32\n")
    f.write("#define CJK_FONT_COUNT %d\n\n" % n)
    f.write("// Unicode codepoints, ascending order (in PROGMEM)\n")
    f.write("static const uint32_t cjk_code_points[CJK_FONT_COUNT] PROGMEM = {\n")
    per = 8
    for i in range(0, n, per):
        line = ", ".join("0x%04X" % cp for cp in code_points[i:i+per])
        f.write("    " + line + ("," if i + per < n else "") + "\n")
    f.write("};\n\n")
    f.write("// Glyph bitmaps, 32 bytes each, parallel to cjk_code_points (in PROGMEM)\n")
    f.write("static const uint8_t cjk_glyphs[CJK_FONT_COUNT * CJK_GLYPH_BYTES] PROGMEM = {\n")
    for i in range(0, len(glyph_bytes), 16):
        chunk = glyph_bytes[i:i+16]
        line = ", ".join("0x%02X" % b for b in chunk)
        f.write("    " + line + ("," if i + 16 < len(glyph_bytes) else "") + "\n")
    f.write("};\n\n")
    f.write("// Binary search: returns glyph index or -1\n")
    f.write("static int cjk_find_glyph(uint32_t cp) {\n")
    f.write("    int lo = 0, hi = CJK_FONT_COUNT - 1;\n")
    f.write("    while (lo <= hi) {\n")
    f.write("        int mid = (lo + hi) / 2;\n")
    f.write("        uint32_t v = pgm_read_dword(&cjk_code_points[mid]);\n")
    f.write("        if (v == cp) return mid;\n")
    f.write("        else if (v < cp) lo = mid + 1;\n")
    f.write("        else hi = mid - 1;\n")
    f.write("    }\n")
    f.write("    return -1;\n")
    f.write("}\n")
print("Wrote", OUT_H, "(%d glyphs)" % n)

# ---- Preview (faithful to firmware blit) ----
def compose_line(text, scale, fg=(0xFF,0xFF,0xFF), bg=(0,0,0)):
    """Compose one line of text using the SAME glyph bytes, scale x."""
    # measure width
    cells = []
    total_w = 0
    i = 0
    while i < len(text):
        # decode UTF-8 char (text is python str already)
        ch = text[i]
        cp = ord(ch)
        idx = -1
        # binary search in code_points
        lo, hi = 0, n - 1
        while lo <= hi:
            mid = (lo + hi) // 2
            if code_points[mid] == cp:
                idx = mid; break
            elif code_points[mid] < cp:
                lo = mid + 1
            else:
                hi = mid - 1
        cells.append((ch, idx))
        total_w += W * scale
        i += 1
    img = Image.new("RGB", (total_w, H * scale), bg)
    px = img.load()
    xoff = 0
    for ch, idx in cells:
        if idx >= 0:
            base = idx * 32
            for r in range(H):
                row = (glyph_bytes[base + r*2] << 8) | glyph_bytes[base + r*2 + 1]
                for c in range(W):
                    if row & (1 << (15 - c)):
                        for dy in range(scale):
                            for dx in range(scale):
                                px[xoff + c*scale + dx, r*scale + dy] = fg
        xoff += W * scale
    return img

test_lines = [
    ("阿莫西林胶囊 一次1片", 2),
    ("头孢克肟分散片 0.5g", 2),
    ("用量：1片（饭后服用）", 2),
    ("维生素C片 100mg", 1),
    ("盐酸二甲双胍缓释片 0.5g", 1),
    ("请按时服药！", 2),
]
pad = 12
line_imgs = [compose_line(t, s) for t, s in test_lines]
total_h = sum(li.height for li in line_imgs) + pad * (len(line_imgs) + 1)
max_w = max(li.width for li in line_imgs) + pad * 2
preview = Image.new("RGB", (max_w, total_h), (0, 0, 0))
y = pad
for li in line_imgs:
    preview.paste(li, (pad, y))
    y += li.height + pad
preview.save(PREVIEW)
print("Wrote preview", PREVIEW)
